name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: cargo install cargo-audit

      - name: cargo audit
        run: cargo audit
