name: Security audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v5
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-audit

      - name: install dependencies
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-audit

      - name: cargo audit
        run: cargo audit
